- name: Unmask required services
  file:
    path: '/etc/systemd/system/{{ item }}'
    state: absent
  loop:
    - console-getty.service
    - systemd-logind.service

- name: Mask tmpfiles.d's selinux setup
  file:
    src: /dev/null
    dest: /etc/tmpfiles.d/selinux-policy.conf
    state: link

- name: Require the documentation to be installed
  lineinfile:
    path: /etc/dnf/dnf.conf
    line: tsflags=nodocs
    state: absent

- import_tasks: build_guest_tools.yaml

- name: Clear the dnf cache
  shell: 'dnf clean all'
  args:
    warn: false
  tags: bend
