- name: Update the package cache
  pacman:
    update_cache: yes
  tags: bend

- name: Install required packages (this may take a while)
  pacman:
    name:
      - inetutils
      - sudo
      - vte-common
