- name: Update the package cache
  pacman:
    update_cache: yes
  tags: bend

- name: Install required packages (this may take a while)
  pacman:
    name:
      - ansible
      - grep
      - inetutils
      - vte-common

- name: Fix the setuid bit on sudo
  file:
    path: /usr/bin/sudo
    mode: 'u+s'

- name: Allow wheel to sudo
  lineinfile:
    path: /etc/sudoers
    regexp: '# (%wheel ALL=\(ALL\) ALL)'
    line: '\1'
    backrefs: true

- name: Delete the cached packages
  shell: 'pacman -Scc --noconfirm'
  tags: bend
