name: Push prebuilt spec files
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'netlify.toml'
      - 'web/**'

jobs:
  push:
    name: Push the spec files
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout the nsbox repo'
        uses: actions/checkout@v1
      - name: 'Run the push'
        uses: ./.github/actions/rpm_spec_files
        with:
          token: '${{ secrets.RPM_SPEC_FILES_TOKEN }}'
