name: Push prebuilt spec files
on:
  push:
    branches:
      - master
  # schedule:
    # - cron: '0 0 * * *'

jobs:
  push:
    name: Push the spec files
    runs-on: ubuntu-latest
    container:
      image: fedora:30
    steps:
      - name: 'Checkout the nsbox repo'
        uses: actions/checkout@v1
      - name: 'Run the push'
        uses: ./.github/actions/rpm_spec_files
        with:
          branch: edge
          token: '${{ secrets.RPM_SPEC_FILES_TOKEN }}'
